name: Feature Request
description: 새로운 기능을 제안해주세요.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 원하는 기능이 무엇인지 설명해주세요.
      placeholder: 어떤 기능이 있으면 좋을지 명확하고 간결하게 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: 사용 케이스
      description: 이 기능을 어떤 상황에서 사용하실 건가요?
      placeholder: |
        이 기능이 해결할 문제나 개선할 워크플로우를 설명해주세요.
        예: "코드 제출 후 결과를 기다리는 동안..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 대안 검토
      description: 다른 대안이나 기능을 고려해보셨나요?
      placeholder: 현재 사용하고 있는 우회 방법이나 대안적인 접근 방식이 있다면 설명해주세요.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 컨텍스트
      description: 기능 요청에 대한 추가적인 정보가 있다면 작성해주세요.
      placeholder: 스크린샷, 다이어그램, 참고 링크 등
    validations:
      required: false
